# Generated by Django 4.1.7 on 2023-08-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Book_Name", models.CharField(max_length=30)),
                ("Author", models.CharField(max_length=40)),
                ("Price", models.IntegerField()),
                ("Discount", models.IntegerField()),
                ("Name_of_person", models.CharField(max_length=30)),
                ("Age", models.IntegerField()),
                ("Rating", models.IntegerField()),
                ("message", models.CharField(max_length=200)),
            ],
        ),
    ]
